/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_gestion_Capteur (void);
GtkWidget* create_capteurs_defectueux (void);
GtkWidget* create_etages_contenant_des_pannes (void);
GtkWidget* create_liste_des_alarmes (void);
GtkWidget* create_window_verif_supp (void);
GtkWidget* create_Gestion_Restau (void);
GtkWidget* create_Ajouter_Etudiant (void);
GtkWidget* create_Gestion_des_Etudiant (void);
GtkWidget* create_Calcul (void);
GtkWidget* create_Modifier_Etudiant (void);
GtkWidget* create_Supprimer_Etudiant (void);
GtkWidget* create_LOGIN (void);
GtkWidget* create_ADMIN (void);
GtkWidget* create_AJOUT (void);
GtkWidget* create_SUPP (void);
GtkWidget* create_RECHERCHE (void);
GtkWidget* create_MODIF (void);
GtkWidget* create_window_acceuil (void);
