/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Ajouter_Etudiant (void);
GtkWidget* create_Gestion_des_Etudiants (void);
GtkWidget* create_Modifier_Etudiant (void);
GtkWidget* create_Calcul (void);
GtkWidget* create_Supprimer_Etudiant (void);
