/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Ajouter_Etudiant (void)
{
  GtkWidget *Ajouter_Etudiant;
  GtkWidget *fixed1;
  GtkWidget *entry_nom;
  GtkWidget *entry_prenom;
  GtkObject *spinbutton_jour_adj;
  GtkWidget *spinbutton_jour;
  GtkObject *spinbutton_mois_adj;
  GtkWidget *spinbutton_mois;
  GtkWidget *entry_chambre;
  GtkWidget *entry_cin;
  GtkWidget *entry_tel;
  GtkObject *spinbutton_annee_adj;
  GtkWidget *spinbutton_annee;
  GtkWidget *entry_adresse;
  GtkWidget *button_return_ajouter;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image20;
  GtkWidget *label36;
  GtkWidget *hseparator4;
  GtkWidget *button_ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label18;
  GtkWidget *label_tel;
  GtkWidget *label_cin;
  GtkWidget *label_chambre;
  GtkWidget *label_adresse;
  GtkWidget *combobox_niveau;
  GtkWidget *label30_spec;
  GtkWidget *label_niveau;
  GtkWidget *radiobutton_homme;
  GSList *radiobutton_homme_group = NULL;
  GtkWidget *label_jour;
  GtkWidget *label_mois;
  GtkWidget *label_prenom;
  GtkWidget *label_naissance;
  GtkWidget *label_genre;
  GtkWidget *label_nom;
  GtkWidget *image27;
  GtkWidget *label_annee;
  GtkWidget *valid_tel;
  GtkWidget *valid_cin;
  GtkWidget *valid_chambre;
  GtkWidget *valid_adres;
  GtkWidget *radiobutton_femme;
  GtkWidget *image28;
  GtkWidget *valid_preno;
  GtkWidget *valid_nom;
  GtkWidget *combobox_spc;

  Ajouter_Etudiant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (Ajouter_Etudiant, "Ajouter_Etudiant");
  gtk_widget_set_size_request (Ajouter_Etudiant, 600, 700);
  gtk_window_set_title (GTK_WINDOW (Ajouter_Etudiant), _("Ajouter un nouveau \303\251tudiant"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_set_name (fixed1, "fixed1");
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Ajouter_Etudiant), fixed1);

  entry_nom = gtk_entry_new ();
  gtk_widget_set_name (entry_nom, "entry_nom");
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_nom, 240, 160);
  gtk_widget_set_size_request (entry_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_prenom = gtk_entry_new ();
  gtk_widget_set_name (entry_prenom, "entry_prenom");
  gtk_widget_show (entry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_prenom, 240, 208);
  gtk_widget_set_size_request (entry_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom), 8226);

  spinbutton_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jour_adj), 1, 0);
  gtk_widget_set_name (spinbutton_jour, "spinbutton_jour");
  gtk_widget_show (spinbutton_jour);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_jour, 288, 256);
  gtk_widget_set_size_request (spinbutton_jour, 40, 24);

  spinbutton_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mois_adj), 1, 0);
  gtk_widget_set_name (spinbutton_mois, "spinbutton_mois");
  gtk_widget_show (spinbutton_mois);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_mois, 384, 256);
  gtk_widget_set_size_request (spinbutton_mois, 40, 24);

  entry_chambre = gtk_entry_new ();
  gtk_widget_set_name (entry_chambre, "entry_chambre");
  gtk_widget_show (entry_chambre);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_chambre, 240, 456);
  gtk_widget_set_size_request (entry_chambre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_chambre), 8226);

  entry_cin = gtk_entry_new ();
  gtk_widget_set_name (entry_cin, "entry_cin");
  gtk_widget_show (entry_cin);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_cin, 240, 512);
  gtk_widget_set_size_request (entry_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin), 8226);

  entry_tel = gtk_entry_new ();
  gtk_widget_set_name (entry_tel, "entry_tel");
  gtk_widget_show (entry_tel);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_tel, 240, 568);
  gtk_widget_set_size_request (entry_tel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_tel), 8226);

  spinbutton_annee_adj = gtk_adjustment_new (1988, 1985, 2005, 1, 10, 10);
  spinbutton_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_annee_adj), 10, 0);
  gtk_widget_set_name (spinbutton_annee, "spinbutton_annee");
  gtk_widget_show (spinbutton_annee);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_annee, 480, 256);
  gtk_widget_set_size_request (spinbutton_annee, 64, 24);

  entry_adresse = gtk_entry_new ();
  gtk_widget_set_name (entry_adresse, "entry_adresse");
  gtk_widget_show (entry_adresse);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_adresse, 240, 408);
  gtk_widget_set_size_request (entry_adresse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_adresse), 8226);

  button_return_ajouter = gtk_button_new ();
  gtk_widget_set_name (button_return_ajouter, "button_return_ajouter");
  gtk_widget_show (button_return_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), button_return_ajouter, 520, 672);
  gtk_widget_set_size_request (button_return_ajouter, 80, 30);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment16, "alignment16");
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_return_ajouter), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox16, "hbox16");
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image20 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image20, "image20");
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox16), image20, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Retour "));
  gtk_widget_set_name (label36, "label36");
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox16), label36, FALSE, FALSE, 0);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator4, "hseparator4");
  gtk_widget_show (hseparator4);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator4, 0, 656);
  gtk_widget_set_size_request (hseparator4, 600, 24);

  button_ajouter = gtk_button_new ();
  gtk_widget_set_name (button_ajouter, "button_ajouter");
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), button_ajouter, 264, 624);
  gtk_widget_set_size_request (button_ajouter, 100, 30);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image1, "image1");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_set_name (label18, "label18");
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox1), label18, FALSE, FALSE, 0);

  label_tel = gtk_label_new (_("N\302\260 Tel :"));
  gtk_widget_set_name (label_tel, "label_tel");
  gtk_widget_show (label_tel);
  gtk_fixed_put (GTK_FIXED (fixed1), label_tel, 152, 568);
  gtk_widget_set_size_request (label_tel, 72, 24);

  label_cin = gtk_label_new (_("N\302\260 CIN :"));
  gtk_widget_set_name (label_cin, "label_cin");
  gtk_widget_show (label_cin);
  gtk_fixed_put (GTK_FIXED (fixed1), label_cin, 144, 512);
  gtk_widget_set_size_request (label_cin, 80, 25);

  label_chambre = gtk_label_new (_("Chambre :"));
  gtk_widget_set_name (label_chambre, "label_chambre");
  gtk_widget_show (label_chambre);
  gtk_fixed_put (GTK_FIXED (fixed1), label_chambre, 136, 456);
  gtk_widget_set_size_request (label_chambre, 80, 25);

  label_adresse = gtk_label_new (_("Adresse mail :"));
  gtk_widget_set_name (label_adresse, "label_adresse");
  gtk_widget_show (label_adresse);
  gtk_fixed_put (GTK_FIXED (fixed1), label_adresse, 104, 408);
  gtk_widget_set_size_request (label_adresse, 120, 25);

  combobox_niveau = gtk_combo_box_new_text ();
  gtk_widget_set_name (combobox_niveau, "combobox_niveau");
  gtk_widget_show (combobox_niveau);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox_niveau, 240, 360);
  gtk_widget_set_size_request (combobox_niveau, 50, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_niveau), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_niveau), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_niveau), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_niveau), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_niveau), _("5"));

  label30_spec = gtk_label_new (_("Sp\303\251cialit\303\251 :"));
  gtk_widget_set_name (label30_spec, "label30_spec");
  gtk_widget_show (label30_spec);
  gtk_fixed_put (GTK_FIXED (fixed1), label30_spec, 296, 360);
  gtk_widget_set_size_request (label30_spec, 80, 24);

  label_niveau = gtk_label_new (_("Niveau :"));
  gtk_widget_set_name (label_niveau, "label_niveau");
  gtk_widget_show (label_niveau);
  gtk_fixed_put (GTK_FIXED (fixed1), label_niveau, 152, 360);
  gtk_widget_set_size_request (label_niveau, 72, 24);

  radiobutton_homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme "));
  gtk_widget_set_name (radiobutton_homme, "radiobutton_homme");
  gtk_widget_show (radiobutton_homme);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton_homme, 240, 304);
  gtk_widget_set_size_request (radiobutton_homme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_homme), radiobutton_homme_group);
  radiobutton_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_homme));

  label_jour = gtk_label_new (_("Jour :"));
  gtk_widget_set_name (label_jour, "label_jour");
  gtk_widget_show (label_jour);
  gtk_fixed_put (GTK_FIXED (fixed1), label_jour, 232, 256);
  gtk_widget_set_size_request (label_jour, 48, 25);

  label_mois = gtk_label_new (_("Mois :"));
  gtk_widget_set_name (label_mois, "label_mois");
  gtk_widget_show (label_mois);
  gtk_fixed_put (GTK_FIXED (fixed1), label_mois, 328, 256);
  gtk_widget_set_size_request (label_mois, 60, 25);

  label_prenom = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_set_name (label_prenom, "label_prenom");
  gtk_widget_show (label_prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), label_prenom, 144, 208);
  gtk_widget_set_size_request (label_prenom, 80, 25);

  label_naissance = gtk_label_new (_("Date de Naissance :"));
  gtk_widget_set_name (label_naissance, "label_naissance");
  gtk_widget_show (label_naissance);
  gtk_fixed_put (GTK_FIXED (fixed1), label_naissance, 80, 256);
  gtk_widget_set_size_request (label_naissance, 136, 25);

  label_genre = gtk_label_new (_("Genre :"));
  gtk_widget_set_name (label_genre, "label_genre");
  gtk_widget_show (label_genre);
  gtk_fixed_put (GTK_FIXED (fixed1), label_genre, 152, 304);
  gtk_widget_set_size_request (label_genre, 70, 24);

  label_nom = gtk_label_new (_("Nom :"));
  gtk_widget_set_name (label_nom, "label_nom");
  gtk_widget_show (label_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), label_nom, 152, 160);
  gtk_widget_set_size_request (label_nom, 80, 25);

  image27 = create_pixmap (Ajouter_Etudiant, "espritii.png");
  gtk_widget_set_name (image27, "image27");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed1), image27, 0, 24);
  gtk_widget_set_size_request (image27, 232, 80);

  label_annee = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_set_name (label_annee, "label_annee");
  gtk_widget_show (label_annee);
  gtk_fixed_put (GTK_FIXED (fixed1), label_annee, 416, 256);
  gtk_widget_set_size_request (label_annee, 80, 25);

  valid_tel = gtk_label_new ("");
  gtk_widget_set_name (valid_tel, "valid_tel");
  gtk_widget_show (valid_tel);
  gtk_fixed_put (GTK_FIXED (fixed1), valid_tel, 408, 568);
  gtk_widget_set_size_request (valid_tel, 80, 25);

  valid_cin = gtk_label_new ("");
  gtk_widget_set_name (valid_cin, "valid_cin");
  gtk_widget_show (valid_cin);
  gtk_fixed_put (GTK_FIXED (fixed1), valid_cin, 408, 512);
  gtk_widget_set_size_request (valid_cin, 80, 25);

  valid_chambre = gtk_label_new ("");
  gtk_widget_set_name (valid_chambre, "valid_chambre");
  gtk_widget_show (valid_chambre);
  gtk_fixed_put (GTK_FIXED (fixed1), valid_chambre, 408, 456);
  gtk_widget_set_size_request (valid_chambre, 80, 25);

  valid_adres = gtk_label_new ("");
  gtk_widget_set_name (valid_adres, "valid_adres");
  gtk_widget_show (valid_adres);
  gtk_fixed_put (GTK_FIXED (fixed1), valid_adres, 408, 408);
  gtk_widget_set_size_request (valid_adres, 80, 25);

  radiobutton_femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme "));
  gtk_widget_set_name (radiobutton_femme, "radiobutton_femme");
  gtk_widget_show (radiobutton_femme);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton_femme, 336, 304);
  gtk_widget_set_size_request (radiobutton_femme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_femme), radiobutton_homme_group);
  radiobutton_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_femme));

  image28 = create_pixmap (Ajouter_Etudiant, "ajout3.png");
  gtk_widget_set_name (image28, "image28");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed1), image28, 480, 8);
  gtk_widget_set_size_request (image28, 112, 112);

  valid_preno = gtk_label_new ("");
  gtk_widget_set_name (valid_preno, "valid_preno");
  gtk_widget_show (valid_preno);
  gtk_fixed_put (GTK_FIXED (fixed1), valid_preno, 408, 208);
  gtk_widget_set_size_request (valid_preno, 70, 25);

  valid_nom = gtk_label_new ("");
  gtk_widget_set_name (valid_nom, "valid_nom");
  gtk_widget_show (valid_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), valid_nom, 400, 160);
  gtk_widget_set_size_request (valid_nom, 80, 25);

  combobox_spc = gtk_combo_box_new_text ();
  gtk_widget_set_name (combobox_spc, "combobox_spc");
  gtk_widget_show (combobox_spc);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox_spc, 376, 360);
  gtk_widget_set_size_request (combobox_spc, 150, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_spc), _("Informatique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_spc), _("G\303\251nie-civile"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_spc), _("TIC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_spc), _("Electrom\303\251canique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_spc), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_spc), "");

  g_signal_connect ((gpointer) button_return_ajouter, "clicked",
                    G_CALLBACK (on_button_return_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_homme, "toggled",
                    G_CALLBACK (on_radiobutton_homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_femme, "toggled",
                    G_CALLBACK (on_radiobutton_femme_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_Etudiant, Ajouter_Etudiant, "Ajouter_Etudiant");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, entry_prenom, "entry_prenom");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, spinbutton_jour, "spinbutton_jour");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, spinbutton_mois, "spinbutton_mois");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, entry_chambre, "entry_chambre");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, entry_cin, "entry_cin");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, entry_tel, "entry_tel");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, spinbutton_annee, "spinbutton_annee");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, entry_adresse, "entry_adresse");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, button_return_ajouter, "button_return_ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, image20, "image20");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label36, "label36");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, image1, "image1");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label18, "label18");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_tel, "label_tel");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_cin, "label_cin");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_chambre, "label_chambre");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_adresse, "label_adresse");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, combobox_niveau, "combobox_niveau");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label30_spec, "label30_spec");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_niveau, "label_niveau");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, radiobutton_homme, "radiobutton_homme");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_jour, "label_jour");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_mois, "label_mois");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_prenom, "label_prenom");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_naissance, "label_naissance");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_genre, "label_genre");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_nom, "label_nom");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, image27, "image27");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, label_annee, "label_annee");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, valid_tel, "valid_tel");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, valid_cin, "valid_cin");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, valid_chambre, "valid_chambre");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, valid_adres, "valid_adres");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, radiobutton_femme, "radiobutton_femme");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, image28, "image28");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, valid_preno, "valid_preno");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, valid_nom, "valid_nom");
  GLADE_HOOKUP_OBJECT (Ajouter_Etudiant, combobox_spc, "combobox_spc");

  return Ajouter_Etudiant;
}

GtkWidget*
create_Gestion_des_Etudiants (void)
{
  GtkWidget *Gestion_des_Etudiants;
  GtkWidget *fixed2;
  GtkWidget *entry_chercher_tab;
  GtkWidget *notebook1;
  GtkWidget *fixed4;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview;
  GtkWidget *label_menu;
  GtkWidget *radiobutton_cher_chambre;
  GSList *radiobutton_cher_chambre_group = NULL;
  GtkWidget *radiobutton_cher_cin;
  GtkWidget *button_chercher_tab;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label24;
  GtkWidget *button_ajouter_tab;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label19;
  GtkWidget *button_modifier_tab;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label20;
  GtkWidget *button_affich_tab;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label22;
  GtkWidget *button_calcul_tab;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image11;
  GtkWidget *label26;
  GtkWidget *button_supprim_tab;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label21;
  GtkWidget *image21;

  Gestion_des_Etudiants = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (Gestion_des_Etudiants, "Gestion_des_Etudiants");
  gtk_window_set_title (GTK_WINDOW (Gestion_des_Etudiants), _("Dashbord"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_set_name (fixed2, "fixed2");
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Gestion_des_Etudiants), fixed2);
  gtk_container_set_border_width (GTK_CONTAINER (fixed2), 10);

  entry_chercher_tab = gtk_entry_new ();
  gtk_widget_set_name (entry_chercher_tab, "entry_chercher_tab");
  gtk_widget_show (entry_chercher_tab);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_chercher_tab, 704, 232);
  gtk_widget_set_size_request (entry_chercher_tab, 94, 30);
  gtk_entry_set_has_frame (GTK_ENTRY (entry_chercher_tab), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_chercher_tab), 8226);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 686, 694);

  fixed4 = gtk_fixed_new ();
  gtk_widget_set_name (fixed4, "fixed4");
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 0, 8);
  gtk_widget_set_size_request (scrolledwindow1, 680, 640);

  treeview = gtk_tree_view_new ();
  gtk_widget_set_name (treeview, "treeview");
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview), TRUE);

  label_menu = gtk_label_new (_("Tous les Etudiants"));
  gtk_widget_set_name (label_menu, "label_menu");
  gtk_widget_show (label_menu);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label_menu);

  radiobutton_cher_chambre = gtk_radio_button_new_with_mnemonic (NULL, _("N\302\260 de Chambre"));
  gtk_widget_set_name (radiobutton_cher_chambre, "radiobutton_cher_chambre");
  gtk_widget_show (radiobutton_cher_chambre);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton_cher_chambre, 792, 176);
  gtk_widget_set_size_request (radiobutton_cher_chambre, 127, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_cher_chambre), radiobutton_cher_chambre_group);
  radiobutton_cher_chambre_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_cher_chambre));

  radiobutton_cher_cin = gtk_radio_button_new_with_mnemonic (NULL, _("CIN"));
  gtk_widget_set_name (radiobutton_cher_cin, "radiobutton_cher_cin");
  gtk_widget_show (radiobutton_cher_cin);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton_cher_cin, 712, 176);
  gtk_widget_set_size_request (radiobutton_cher_cin, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_cher_cin), radiobutton_cher_chambre_group);
  radiobutton_cher_chambre_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_cher_cin));

  button_chercher_tab = gtk_button_new ();
  gtk_widget_set_name (button_chercher_tab, "button_chercher_tab");
  gtk_widget_show (button_chercher_tab);
  gtk_fixed_put (GTK_FIXED (fixed2), button_chercher_tab, 832, 232);
  gtk_widget_set_size_request (button_chercher_tab, 90, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment6, "alignment6");
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_chercher_tab), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image9, "image9");
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_set_name (label24, "label24");
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox6), label24, FALSE, FALSE, 0);

  button_ajouter_tab = gtk_button_new ();
  gtk_widget_set_name (button_ajouter_tab, "button_ajouter_tab");
  gtk_widget_show (button_ajouter_tab);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ajouter_tab, 704, 360);
  gtk_widget_set_size_request (button_ajouter_tab, 100, 30);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_ajouter_tab), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image2, "image2");
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_set_name (label19, "label19");
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox2), label19, FALSE, FALSE, 0);

  button_modifier_tab = gtk_button_new ();
  gtk_widget_set_name (button_modifier_tab, "button_modifier_tab");
  gtk_widget_show (button_modifier_tab);
  gtk_fixed_put (GTK_FIXED (fixed2), button_modifier_tab, 816, 360);
  gtk_widget_set_size_request (button_modifier_tab, 100, 30);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_modifier_tab), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image4, "image4");
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_set_name (label20, "label20");
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox3), label20, FALSE, FALSE, 0);

  button_affich_tab = gtk_button_new ();
  gtk_widget_set_name (button_affich_tab, "button_affich_tab");
  gtk_widget_show (button_affich_tab);
  gtk_fixed_put (GTK_FIXED (fixed2), button_affich_tab, 704, 448);
  gtk_widget_set_size_request (button_affich_tab, 100, 30);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment5, "alignment5");
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_affich_tab), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-print-preview", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image6, "image6");
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_set_name (label22, "label22");
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox5), label22, FALSE, FALSE, 0);

  button_calcul_tab = gtk_button_new ();
  gtk_widget_set_name (button_calcul_tab, "button_calcul_tab");
  gtk_widget_show (button_calcul_tab);
  gtk_fixed_put (GTK_FIXED (fixed2), button_calcul_tab, 816, 448);
  gtk_widget_set_size_request (button_calcul_tab, 100, 30);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment8, "alignment8");
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_calcul_tab), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox8, "hbox8");
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image11 = gtk_image_new_from_stock ("gtk-zoom-100", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image11, "image11");
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox8), image11, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Calcul"));
  gtk_widget_set_name (label26, "label26");
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox8), label26, FALSE, FALSE, 0);

  button_supprim_tab = gtk_button_new ();
  gtk_widget_set_name (button_supprim_tab, "button_supprim_tab");
  gtk_widget_show (button_supprim_tab);
  gtk_fixed_put (GTK_FIXED (fixed2), button_supprim_tab, 760, 552);
  gtk_widget_set_size_request (button_supprim_tab, 100, 30);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment4, "alignment4");
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_supprim_tab), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image5, "image5");
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_set_name (label21, "label21");
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox4), label21, FALSE, FALSE, 0);

  image21 = create_pixmap (Gestion_des_Etudiants, "Sans titre 1.png");
  gtk_widget_set_name (image21, "image21");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed2), image21, 704, 0);
  gtk_widget_set_size_request (image21, 280, 136);

  g_signal_connect ((gpointer) treeview, "row_activated",
                    G_CALLBACK (on_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_cher_chambre, "toggled",
                    G_CALLBACK (on_radiobutton_cher_chambre_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_cher_cin, "toggled",
                    G_CALLBACK (on_radiobutton_cher_cin_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_chercher_tab, "clicked",
                    G_CALLBACK (on_button_chercher_tab_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_tab, "clicked",
                    G_CALLBACK (on_button_ajouter_tab_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_tab, "clicked",
                    G_CALLBACK (on_button_modifier_tab_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affich_tab, "clicked",
                    G_CALLBACK (on_button_affich_tab_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_calcul_tab, "clicked",
                    G_CALLBACK (on_button_calcul_tab_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprim_tab, "clicked",
                    G_CALLBACK (on_button_supprim_tab_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_Etudiants, Gestion_des_Etudiants, "Gestion_des_Etudiants");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, entry_chercher_tab, "entry_chercher_tab");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, label_menu, "label_menu");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, radiobutton_cher_chambre, "radiobutton_cher_chambre");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, radiobutton_cher_cin, "radiobutton_cher_cin");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, button_chercher_tab, "button_chercher_tab");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, image9, "image9");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, label24, "label24");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, button_ajouter_tab, "button_ajouter_tab");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, image2, "image2");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, label19, "label19");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, button_modifier_tab, "button_modifier_tab");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, image4, "image4");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, label20, "label20");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, button_affich_tab, "button_affich_tab");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, image6, "image6");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, label22, "label22");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, button_calcul_tab, "button_calcul_tab");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, image11, "image11");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, label26, "label26");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, button_supprim_tab, "button_supprim_tab");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, image5, "image5");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, label21, "label21");
  GLADE_HOOKUP_OBJECT (Gestion_des_Etudiants, image21, "image21");

  gtk_widget_grab_default (radiobutton_cher_chambre);
  return Gestion_des_Etudiants;
}

GtkWidget*
create_Modifier_Etudiant (void)
{
  GtkWidget *Modifier_Etudiant;
  GtkWidget *fixed3;
  GtkWidget *entry_modif_nom;
  GtkWidget *entry_modif_prenom;
  GtkWidget *entry_modif_chambre;
  GtkWidget *entry_modif_tel;
  GtkWidget *image22;
  GtkWidget *hseparator3;
  GtkWidget *label_modif_niveau;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton5;
  GtkWidget *label_modif_prenom;
  GtkWidget *label_modif_nom;
  GtkWidget *label_modif_chambre;
  GtkWidget *label_modif_tel;
  GtkWidget *button_return_modifier;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image18;
  GtkWidget *label33;
  GtkWidget *image26;
  GtkWidget *button_modif_enregistrer;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label34;
  GtkWidget *button_modifier;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image17;
  GtkWidget *label32;
  GtkWidget *image25;

  Modifier_Etudiant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (Modifier_Etudiant, "Modifier_Etudiant");
  gtk_widget_set_size_request (Modifier_Etudiant, 520, 700);
  gtk_window_set_title (GTK_WINDOW (Modifier_Etudiant), _("Modifier un \303\251tudiant"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_set_name (fixed3, "fixed3");
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Modifier_Etudiant), fixed3);
  gtk_widget_set_size_request (fixed3, 404, 500);
  gtk_container_set_border_width (GTK_CONTAINER (fixed3), 10);

  entry_modif_nom = gtk_entry_new ();
  gtk_widget_set_name (entry_modif_nom, "entry_modif_nom");
  gtk_widget_show (entry_modif_nom);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_modif_nom, 200, 224);
  gtk_widget_set_size_request (entry_modif_nom, 120, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_nom), 8226);

  entry_modif_prenom = gtk_entry_new ();
  gtk_widget_set_name (entry_modif_prenom, "entry_modif_prenom");
  gtk_widget_show (entry_modif_prenom);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_modif_prenom, 200, 304);
  gtk_widget_set_size_request (entry_modif_prenom, 120, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_prenom), 8226);

  entry_modif_chambre = gtk_entry_new ();
  gtk_widget_set_name (entry_modif_chambre, "entry_modif_chambre");
  gtk_widget_show (entry_modif_chambre);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_modif_chambre, 200, 448);
  gtk_widget_set_size_request (entry_modif_chambre, 120, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_chambre), 8226);

  entry_modif_tel = gtk_entry_new ();
  gtk_widget_set_name (entry_modif_tel, "entry_modif_tel");
  gtk_widget_show (entry_modif_tel);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_modif_tel, 200, 520);
  gtk_widget_set_size_request (entry_modif_tel, 120, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_tel), 8226);

  image22 = create_pixmap (Modifier_Etudiant, "modif.png");
  gtk_widget_set_name (image22, "image22");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed3), image22, 720, 32);
  gtk_widget_set_size_request (image22, 150, 318);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator3, "hseparator3");
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator3, 16, 632);
  gtk_widget_set_size_request (hseparator3, 526, 30);

  label_modif_niveau = gtk_label_new (_("Niveau :"));
  gtk_widget_set_name (label_modif_niveau, "label_modif_niveau");
  gtk_widget_show (label_modif_niveau);
  gtk_fixed_put (GTK_FIXED (fixed3), label_modif_niveau, 80, 376);
  gtk_widget_set_size_request (label_modif_niveau, 70, 25);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("1ere"));
  gtk_widget_set_name (radiobutton1, "radiobutton1");
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1, 152, 376);
  gtk_widget_set_size_request (radiobutton1, 65, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("2\303\250me"));
  gtk_widget_set_name (radiobutton2, "radiobutton2");
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2, 216, 376);
  gtk_widget_set_size_request (radiobutton2, 65, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("3\303\250me"));
  gtk_widget_set_name (radiobutton3, "radiobutton3");
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton3, 288, 376);
  gtk_widget_set_size_request (radiobutton3, 65, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("4\303\250me"));
  gtk_widget_set_name (radiobutton4, "radiobutton4");
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton4, 360, 376);
  gtk_widget_set_size_request (radiobutton4, 65, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("5\303\250me"));
  gtk_widget_set_name (radiobutton5, "radiobutton5");
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton5, 432, 376);
  gtk_widget_set_size_request (radiobutton5, 65, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  label_modif_prenom = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_set_name (label_modif_prenom, "label_modif_prenom");
  gtk_widget_show (label_modif_prenom);
  gtk_fixed_put (GTK_FIXED (fixed3), label_modif_prenom, 80, 296);
  gtk_widget_set_size_request (label_modif_prenom, 70, 25);

  label_modif_nom = gtk_label_new (_("Nom :"));
  gtk_widget_set_name (label_modif_nom, "label_modif_nom");
  gtk_widget_show (label_modif_nom);
  gtk_fixed_put (GTK_FIXED (fixed3), label_modif_nom, 96, 224);
  gtk_widget_set_size_request (label_modif_nom, 60, 25);

  label_modif_chambre = gtk_label_new (_("Chambre :"));
  gtk_widget_set_name (label_modif_chambre, "label_modif_chambre");
  gtk_widget_show (label_modif_chambre);
  gtk_fixed_put (GTK_FIXED (fixed3), label_modif_chambre, 72, 448);
  gtk_widget_set_size_request (label_modif_chambre, 70, 25);

  label_modif_tel = gtk_label_new (_("N\302\260Tel :"));
  gtk_widget_set_name (label_modif_tel, "label_modif_tel");
  gtk_widget_show (label_modif_tel);
  gtk_fixed_put (GTK_FIXED (fixed3), label_modif_tel, 88, 520);
  gtk_widget_set_size_request (label_modif_tel, 62, 30);

  button_return_modifier = gtk_button_new ();
  gtk_widget_set_name (button_return_modifier, "button_return_modifier");
  gtk_widget_show (button_return_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), button_return_modifier, 424, 648);
  gtk_widget_set_size_request (button_return_modifier, 80, 30);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment14, "alignment14");
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_return_modifier), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox14, "hbox14");
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image18 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image18, "image18");
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox14), image18, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_set_name (label33, "label33");
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox14), label33, FALSE, FALSE, 0);

  image26 = create_pixmap (Modifier_Etudiant, "espritii.png");
  gtk_widget_set_name (image26, "image26");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed3), image26, 0, 8);
  gtk_widget_set_size_request (image26, 214, 78);

  button_modif_enregistrer = gtk_button_new ();
  gtk_widget_set_name (button_modif_enregistrer, "button_modif_enregistrer");
  gtk_widget_show (button_modif_enregistrer);
  gtk_fixed_put (GTK_FIXED (fixed3), button_modif_enregistrer, 232, 600);
  gtk_widget_set_size_request (button_modif_enregistrer, 60, 30);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment15, "alignment15");
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_modif_enregistrer), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox15, "hbox15");
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image19 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image19, "image19");
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_set_name (label34, "label34");
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox15), label34, FALSE, FALSE, 0);

  button_modifier = gtk_button_new ();
  gtk_widget_set_name (button_modifier, "button_modifier");
  gtk_widget_show (button_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), button_modifier, 160, 136);
  gtk_widget_set_size_request (button_modifier, 206, 38);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment13, "alignment13");
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_modifier), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox13, "hbox13");
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image17 = gtk_image_new_from_stock ("gtk-underline", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image17, "image17");
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox13), image17, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("<b><span color='green'> Etudiant S\303\251lectionn\303\251</span></b> "));
  gtk_widget_set_name (label32, "label32");
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox13), label32, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  image25 = create_pixmap (Modifier_Etudiant, "modif.png");
  gtk_widget_set_name (image25, "image25");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed3), image25, 400, 0);
  gtk_widget_set_size_request (image25, 97, 94);

  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_return_modifier, "clicked",
                    G_CALLBACK (on_button_return_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modif_enregistrer, "clicked",
                    G_CALLBACK (on_button_modif_enregistrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier_Etudiant, Modifier_Etudiant, "Modifier_Etudiant");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, entry_modif_nom, "entry_modif_nom");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, entry_modif_prenom, "entry_modif_prenom");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, entry_modif_chambre, "entry_modif_chambre");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, entry_modif_tel, "entry_modif_tel");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, image22, "image22");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, label_modif_niveau, "label_modif_niveau");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, label_modif_prenom, "label_modif_prenom");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, label_modif_nom, "label_modif_nom");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, label_modif_chambre, "label_modif_chambre");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, label_modif_tel, "label_modif_tel");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, button_return_modifier, "button_return_modifier");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, image18, "image18");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, label33, "label33");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, image26, "image26");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, button_modif_enregistrer, "button_modif_enregistrer");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, image19, "image19");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, label34, "label34");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, button_modifier, "button_modifier");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, image17, "image17");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, label32, "label32");
  GLADE_HOOKUP_OBJECT (Modifier_Etudiant, image25, "image25");

  return Modifier_Etudiant;
}

GtkWidget*
create_Calcul (void)
{
  GtkWidget *Calcul;
  GtkWidget *fixed5;
  GtkWidget *checkbutton_calcul_4;
  GtkWidget *checkbutton_calcul_3;
  GtkWidget *checkbutton_calcul_2;
  GtkWidget *checkbutton_calcul_1;
  GtkWidget *button_calcul_sum;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image15;
  GtkWidget *label30;
  GtkWidget *label_calcul_s;
  GtkWidget *button_retour_home;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image16;
  GtkWidget *label31;
  GtkWidget *hseparator1;
  GtkWidget *checkbutton_calcul_5;
  GtkWidget *image24;
  GtkWidget *image23;
  GtkWidget *label35;

  Calcul = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (Calcul, "Calcul");
  gtk_widget_set_size_request (Calcul, 500, 430);
  gtk_window_set_title (GTK_WINDOW (Calcul), _("Calculer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_set_name (fixed5, "fixed5");
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Calcul), fixed5);
  gtk_container_set_border_width (GTK_CONTAINER (fixed5), 10);

  checkbutton_calcul_4 = gtk_check_button_new_with_mnemonic (_("4\303\250me"));
  gtk_widget_set_name (checkbutton_calcul_4, "checkbutton_calcul_4");
  gtk_widget_show (checkbutton_calcul_4);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_calcul_4, 320, 168);
  gtk_widget_set_size_request (checkbutton_calcul_4, 65, 30);

  checkbutton_calcul_3 = gtk_check_button_new_with_mnemonic (_("3\303\250me"));
  gtk_widget_set_name (checkbutton_calcul_3, "checkbutton_calcul_3");
  gtk_widget_show (checkbutton_calcul_3);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_calcul_3, 224, 168);
  gtk_widget_set_size_request (checkbutton_calcul_3, 65, 30);

  checkbutton_calcul_2 = gtk_check_button_new_with_mnemonic (_("2\303\250me"));
  gtk_widget_set_name (checkbutton_calcul_2, "checkbutton_calcul_2");
  gtk_widget_show (checkbutton_calcul_2);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_calcul_2, 128, 168);
  gtk_widget_set_size_request (checkbutton_calcul_2, 65, 30);

  checkbutton_calcul_1 = gtk_check_button_new_with_mnemonic (_("1\303\250re"));
  gtk_widget_set_name (checkbutton_calcul_1, "checkbutton_calcul_1");
  gtk_widget_show (checkbutton_calcul_1);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_calcul_1, 40, 168);
  gtk_widget_set_size_request (checkbutton_calcul_1, 65, 30);

  button_calcul_sum = gtk_button_new ();
  gtk_widget_set_name (button_calcul_sum, "button_calcul_sum");
  gtk_widget_show (button_calcul_sum);
  gtk_fixed_put (GTK_FIXED (fixed5), button_calcul_sum, 216, 248);
  gtk_widget_set_size_request (button_calcul_sum, 82, 30);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment11, "alignment11");
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_calcul_sum), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox11, "hbox11");
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image15 = gtk_image_new_from_stock ("gtk-zoom-in", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image15, "image15");
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox11), image15, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Calculer"));
  gtk_widget_set_name (label30, "label30");
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox11), label30, FALSE, FALSE, 0);

  label_calcul_s = gtk_label_new ("");
  gtk_widget_set_name (label_calcul_s, "label_calcul_s");
  gtk_widget_show (label_calcul_s);
  gtk_fixed_put (GTK_FIXED (fixed5), label_calcul_s, 144, 328);
  gtk_widget_set_size_request (label_calcul_s, 238, 32);

  button_retour_home = gtk_button_new ();
  gtk_widget_set_name (button_retour_home, "button_retour_home");
  gtk_widget_show (button_retour_home);
  gtk_fixed_put (GTK_FIXED (fixed5), button_retour_home, 408, 384);
  gtk_widget_set_size_request (button_retour_home, 80, 30);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment12, "alignment12");
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_retour_home), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox12, "hbox12");
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image16 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image16, "image16");
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox12), image16, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_set_name (label31, "label31");
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox12), label31, FALSE, FALSE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed5), hseparator1, 0, 376);
  gtk_widget_set_size_request (hseparator1, 518, 22);

  checkbutton_calcul_5 = gtk_check_button_new_with_mnemonic (_("5\303\250me"));
  gtk_widget_set_name (checkbutton_calcul_5, "checkbutton_calcul_5");
  gtk_widget_show (checkbutton_calcul_5);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_calcul_5, 400, 168);
  gtk_widget_set_size_request (checkbutton_calcul_5, 65, 30);

  image24 = create_pixmap (Calcul, "espritii.png");
  gtk_widget_set_name (image24, "image24");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed5), image24, 0, 0);
  gtk_widget_set_size_request (image24, 214, 78);

  image23 = create_pixmap (Calcul, "calcul.png");
  gtk_widget_set_name (image23, "image23");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed5), image23, 424, 8);
  gtk_widget_set_size_request (image23, 59, 62);

  label35 = gtk_label_new (_("<span foreground='#5F9EA0'><b> S\303\251l\303\251ctionner le Niveau : </b></span>"));
  gtk_widget_set_name (label35, "label35");
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed5), label35, 160, 104);
  gtk_widget_set_size_request (label35, 230, 30);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  g_signal_connect ((gpointer) checkbutton_calcul_4, "toggled",
                    G_CALLBACK (on_checkbutton_calcul_4_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_calcul_3, "toggled",
                    G_CALLBACK (on_checkbutton_calcul_3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_calcul_2, "toggled",
                    G_CALLBACK (on_checkbutton_calcul_2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_calcul_1, "toggled",
                    G_CALLBACK (on_checkbutton_calcul_1_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_calcul_sum, "clicked",
                    G_CALLBACK (on_button_calcul_sum_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_home, "clicked",
                    G_CALLBACK (on_button_retour_home_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_calcul_5, "toggled",
                    G_CALLBACK (on_checkbutton_calcul_5_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Calcul, Calcul, "Calcul");
  GLADE_HOOKUP_OBJECT (Calcul, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Calcul, checkbutton_calcul_4, "checkbutton_calcul_4");
  GLADE_HOOKUP_OBJECT (Calcul, checkbutton_calcul_3, "checkbutton_calcul_3");
  GLADE_HOOKUP_OBJECT (Calcul, checkbutton_calcul_2, "checkbutton_calcul_2");
  GLADE_HOOKUP_OBJECT (Calcul, checkbutton_calcul_1, "checkbutton_calcul_1");
  GLADE_HOOKUP_OBJECT (Calcul, button_calcul_sum, "button_calcul_sum");
  GLADE_HOOKUP_OBJECT (Calcul, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Calcul, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Calcul, image15, "image15");
  GLADE_HOOKUP_OBJECT (Calcul, label30, "label30");
  GLADE_HOOKUP_OBJECT (Calcul, label_calcul_s, "label_calcul_s");
  GLADE_HOOKUP_OBJECT (Calcul, button_retour_home, "button_retour_home");
  GLADE_HOOKUP_OBJECT (Calcul, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Calcul, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Calcul, image16, "image16");
  GLADE_HOOKUP_OBJECT (Calcul, label31, "label31");
  GLADE_HOOKUP_OBJECT (Calcul, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (Calcul, checkbutton_calcul_5, "checkbutton_calcul_5");
  GLADE_HOOKUP_OBJECT (Calcul, image24, "image24");
  GLADE_HOOKUP_OBJECT (Calcul, image23, "image23");
  GLADE_HOOKUP_OBJECT (Calcul, label35, "label35");

  return Calcul;
}

GtkWidget*
create_Supprimer_Etudiant (void)
{
  GtkWidget *Supprimer_Etudiant;
  GtkWidget *fixed6;
  GtkWidget *button_oui_supprimer;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image14;
  GtkWidget *label29;
  GtkWidget *button_nom_supprimer;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image13;
  GtkWidget *label28;
  GtkWidget *label_supprimer;

  Supprimer_Etudiant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (Supprimer_Etudiant, "Supprimer_Etudiant");
  gtk_widget_set_size_request (Supprimer_Etudiant, 400, 350);
  gtk_window_set_title (GTK_WINDOW (Supprimer_Etudiant), _("Supprimer un \303\251tudiant"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_set_name (fixed6, "fixed6");
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Supprimer_Etudiant), fixed6);
  gtk_widget_set_size_request (fixed6, 400, 235);
  gtk_container_set_border_width (GTK_CONTAINER (fixed6), 10);

  button_oui_supprimer = gtk_button_new ();
  gtk_widget_set_name (button_oui_supprimer, "button_oui_supprimer");
  gtk_widget_show (button_oui_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), button_oui_supprimer, 208, 192);
  gtk_widget_set_size_request (button_oui_supprimer, 60, 30);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment10, "alignment10");
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_oui_supprimer), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox10, "hbox10");
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image14, "image14");
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox10), image14, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("OUI"));
  gtk_widget_set_name (label29, "label29");
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox10), label29, FALSE, FALSE, 0);

  button_nom_supprimer = gtk_button_new ();
  gtk_widget_set_name (button_nom_supprimer, "button_nom_supprimer");
  gtk_widget_show (button_nom_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), button_nom_supprimer, 128, 192);
  gtk_widget_set_size_request (button_nom_supprimer, 60, 30);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment9, "alignment9");
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_nom_supprimer), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox9, "hbox9");
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image13 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image13, "image13");
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox9), image13, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("NON"));
  gtk_widget_set_name (label28, "label28");
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox9), label28, FALSE, FALSE, 0);

  label_supprimer = gtk_label_new (_("<span foreground=\"red\"><b> Voulez-vous vraiment Supprimer cet Etudiant ?</b></span>"));
  gtk_widget_set_name (label_supprimer, "label_supprimer");
  gtk_widget_show (label_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), label_supprimer, 24, 112);
  gtk_widget_set_size_request (label_supprimer, 352, 48);
  gtk_label_set_use_markup (GTK_LABEL (label_supprimer), TRUE);

  g_signal_connect ((gpointer) button_oui_supprimer, "clicked",
                    G_CALLBACK (on_button_oui_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_nom_supprimer, "clicked",
                    G_CALLBACK (on_button_nom_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer_Etudiant, Supprimer_Etudiant, "Supprimer_Etudiant");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, button_oui_supprimer, "button_oui_supprimer");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, image14, "image14");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, label29, "label29");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, button_nom_supprimer, "button_nom_supprimer");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, image13, "image13");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, label28, "label28");
  GLADE_HOOKUP_OBJECT (Supprimer_Etudiant, label_supprimer, "label_supprimer");

  return Supprimer_Etudiant;
}

